### ISSUE TITLE
Simulating a spin system with many sublattices

### ISSUE THREAD

**Issue by amirhemmatzade** [abehersan/CEFOracle#8]
Hi,
I'm trying to simulate a spin system with four sublattices with their spin anisotropy not parallel to the lab coordinate system.
I was wondering how it can be done? In particular I am interested in magnetisation and susceptibility of a single crystal.

**Comment by abehersan** [comment]
Hi Amir!
In the most recent version of the `dev` branch eb511bc647ccbd5b00ac4286ab31cdf93e3feb33 I added a first attempt at a multisite CEF calculation framework.

Below is a minimal working example of how a calculation should look like. 

We can discuss further the newly added functions `cef_X_multisite` were `X` is any of magnetization, susceptibility and neutronxsection.


```julia
using CEFOracle, Plots

ion = single_ion("Ho3")
bfactors1 = blm_dframe(Dict("B20"=>-0.089e-1))
bfactors2 = blm_dframe(Dict("B20"=>-2.089e-3))
sites_vecB = [cef_site(ion, bfactors1, 0.5, [1,0,0]), cef_site(ion, bfactors2, 0.5, [0,1,0])] # factors 0.5 are the site_ratios
cef_eigensystem_multisite(sites_vecB, verbose=true);

energy_transfer = -2:0.01:2
insx_powder = [cef_neutronxsection_multisite(sites_vecB, en, 2.55, 2.0) for en in energy_transfer]

p = plot(xlabel="Energy [meV]", ylabel="Calc. Intensity [arb. units]")
plot(p, energy_transfer, insx_powder, label="INS-XSECTION Ho3+ Multisite")
```
